import { createContext, useContext, useState, useEffect } from 'react';

// Available languages with their display names and flags
export const availableLanguages = [
  { code: 'en', name: 'English', flag: '🇺🇸', nativeName: 'English' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
  { code: 'fr', name: 'French', flag: '🇫🇷', nativeName: 'Français' },
  { code: 'pt', name: 'Portuguese', flag: '🇧🇷', nativeName: 'Português' },
  { code: 'de', name: 'German', flag: '🇩🇪', nativeName: 'Deutsch' },
  { code: 'it', name: 'Italian', flag: '🇮🇹', nativeName: 'Italiano' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳', nativeName: '中文' },
];

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    planner: 'Lesson Planner',
    attendance: 'Attendance',
    gradebook: 'Gradebook',
    classes: 'Classes',
    settings: 'Settings',
    logout: 'Logout',
    
    // Auth
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    signInWithGoogle: 'Sign in with Google',
    orContinueWith: 'or continue with',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    
    // Dashboard
    welcome: 'Welcome',
    todayOverview: "Today's Overview",
    quickActions: 'Quick Actions',
    attendancePending: 'Attendance Pending',
    upcomingAssignments: 'Upcoming Assignments',
    recentPlans: 'Recent Plans',
    totalClasses: 'Total Classes',
    totalStudents: 'Total Students',
    totalPlans: 'Total Plans',
    
    // Classes
    addClass: 'Add Class',
    className: 'Class Name',
    grade: 'Grade',
    section: 'Section',
    subject: 'Subject',
    yearTerm: 'Year/Term',
    students: 'Students',
    addStudent: 'Add Student',
    firstName: 'First Name',
    lastName: 'Last Name',
    studentNumber: 'Student Number',
    parentEmail: 'Parent Email',
    notes: 'Notes',
    accommodations: 'Accommodations',
    
    // Planner
    weeklyPlan: 'Weekly Plan',
    createPlan: 'Create Plan',
    weekOf: 'Week of',
    unit: 'Unit',
    story: 'Story/Title',
    objectiveOfWeek: 'Objective of the Week',
    skillsOfWeek: 'Skills of the Week',
    dayTheme: 'Day Theme',
    activities: 'Activities',
    materials: 'Materials',
    standards: 'Standards',
    expectations: 'Expectations',
    firstWeek: 'First Week',
    secondWeek: 'Second Week',
    saveAsTemplate: 'Save as Template',
    duplicateLastWeek: 'Duplicate Last Week',
    exportPdf: 'Export PDF',
    
    // Taxonomy levels
    level1Memory: 'Level 1: Memory',
    level2Processing: 'Level 2: Processing',
    level3Strategic: 'Level 3: Strategic Thinking',
    level4Extended: 'Level 4: Extended Thinking',
    
    // Activities
    brainstorming: 'Brainstorming',
    buildingBackground: 'Building Background',
    vocabularyDevelopment: 'Vocabulary Development',
    readPages: 'Read Pages',
    guidedReading: 'Guided & Choral Reading',
    oralQuestions: 'Oral Questions',
    comprehensionQuestions: 'Comprehension Questions',
    exercisePractice: 'Exercise Practice',
    other: 'Other',
    
    // Materials
    book: 'Book',
    notebook: 'Notebook',
    teachersGuide: "Teacher's Guide",
    testQuiz: 'Test/Quiz',
    dictionary: 'Dictionary',
    handouts: 'Handouts',
    
    // Standards domains
    listeningAndSpeaking: 'Listening/Speaking',
    foundationalSkills: 'Foundational Skills',
    reading: 'Reading',
    writing: 'Writing',
    language: 'Language',
    
    // Subject integration
    mathematics: 'Mathematics',
    spanish: 'Spanish',
    socialStudies: 'Social Studies',
    science: 'Science',
    health: 'Health',
    art: 'Art',
    physicalEducation: 'Physical Education',
    religion: 'Religion',
    
    // Attendance
    takeAttendance: 'Take Attendance',
    present: 'Present',
    absent: 'Absent',
    tardy: 'Tardy',
    excused: 'Excused',
    markAllPresent: 'Mark All Present',
    submitAttendance: 'Submit Attendance',
    attendanceReport: 'Attendance Report',
    
    // Gradebook
    assignments: 'Assignments',
    createAssignment: 'Create Assignment',
    title: 'Title',
    description: 'Description',
    points: 'Points',
    dueDate: 'Due Date',
    category: 'Category',
    homework: 'Homework',
    quiz: 'Quiz',
    test: 'Test',
    project: 'Project',
    gradeEntry: 'Grade Entry',
    missing: 'Missing',
    late: 'Late',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    search: 'Search',
    filter: 'Filter',
    loading: 'Loading...',
    noData: 'No data available',
    confirmDelete: 'Are you sure you want to delete this?',
    success: 'Success',
    error: 'Error',
    from: 'From',
    to: 'To',
    date: 'Date',
    teacher: 'Teacher',
    selectLanguage: 'Select Language',
    
    // Days
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    
    // Games
    educationalGames: 'Educational Games',
    myGames: 'My Games',
    createGame: 'Create Game',
    play: 'Play',
    copyLink: 'Copy Link',
    shareToClassroom: 'Share to Classroom',
    deleteGame: 'Delete Game',
    questions: 'Questions',
    gameType: 'Game Type',
    gradeLevel: 'Grade Level',
    
    // Landing Page
    landingHeroTitle: 'Your complete classroom in one platform',
    landingHeroSubtitle: 'Lesson planning, attendance, gradebook, and AI assistant. Everything a teacher needs, in one place.',
    landingBuiltForTeachers: 'Built for teachers',
    landingStartFree: 'Start free',
    landingViewPricing: 'View pricing',
    landingUsedBySchools: 'Used by schools in Puerto Rico and beyond',
    landingEverythingYouNeed: 'Everything you need',
    landingEverythingDesc: 'A complete platform designed specifically for teachers.',
    landingFeatures: 'Features',
    landingAiAssistant: 'AI Assistant',
    landingHomeschool: 'Homeschool',
    landingIntegrations: 'Integrations',
    landingCustomization: 'Customization',
    landingPricing: 'Pricing',
    landingGetStarted: 'Get Started - Log In',
    landingStart: 'Start',
    landingAiLessonPlan: 'AI Lesson Plan',
    landingPresentations: 'Presentations',
    landingGrades: 'Grades',
    landingPlanFaster: 'Plan faster',
    landingPlanFasterDesc: 'Create weekly lesson plans in seconds with our intuitive format.',
    landingWeek1: 'Week 1',
    landingYourBrand: 'Your brand, your style',
    landingYourBrandDesc: "Customize with your school's logo and colors on all documents.",
    landingYourSchool: 'Your School',
    landingCustomBranding: 'Custom branding',
    landingExportPro: 'Export professionally',
    landingExportProDesc: 'Generate PDFs ready to print: plans, report cards, substitute packets.',
    landingDownloadPdf: 'Download PDF',
    landingAiAssistantTitle: 'AI Assistant',
    landingAiAssistantDesc: 'Generate lesson plans, activities, questions and more with AI.',
    landingLessonPlans: 'Lesson plans',
    landingQuizzesTests: 'Quizzes & tests',
    landingDigitalClassroom: 'Your digital classroom',
    landingTryFree: 'Try free for 30 days',
    landingNoCard: 'No credit card required',
    landingFullName: 'Full Name',
    landingCreateAccount: 'Create Free Account',
    landingOrLoginWith: 'Or login with',
    landingHaveAccount: 'Have an account?',
    landingLoginHere: 'Login here',
    landingNeedAccount: 'Need account?',
    landingRegisterHere: 'Register here',
    // AI Section
    landingAiTeachingAssistant: 'AI Teaching Assistant',
    landingYouAsked: 'You asked:',
    landingAiResponse: 'AI Response:',
    landingAiQuestion: 'How can I teach equivalent fractions to 4th grade?',
    landingAiAnswer: "Here's a lesson plan based on CCSS.MATH.4.NF.A.1 standard with hands-on activities...",
    landingQuizzes: 'Quizzes',
    landingWorksheets: 'Worksheets',
    landingIdeas: 'Ideas',
    landingNewAi: 'New: Artificial Intelligence',
    landingAiAssistantToTeach: 'Your AI assistant to teach better',
    landingAiAssistantDesc2: 'Generate lesson plans, quizzes, summaries, and activities based on Common Core and Puerto Rico standards, instantly.',
    landingAlignedStandards: 'Aligned with Common Core & PR CORE',
    landingGenerateSeconds: 'Generate content in seconds',
    landingBilingual: 'Bilingual: Spanish & English',
    landingPoweredBy: 'Powered by Claude Sonnet 4.5',
    landingTryItFree: 'Try it free',
    landingIncludedSubscription: 'Included in subscription',
    // Integrations Section
    landingConnectTools: 'Connect with your favorite tools',
    landingConnectToolsDesc: 'Integrate with platforms you already use to make your workflow even easier.',
    landingCalendarSync: 'Calendar Sync',
    landingCalendarSyncDesc: 'Export your lesson plans to Google Calendar, Outlook, or Apple Calendar.',
    landingGoogleClassroom: 'Google Classroom',
    landingGoogleClassroomDesc: 'Share activities and games directly with your students.',
    landingPdfExport: 'PDF Export',
    landingPdfExportDesc: 'Generate professional PDFs for plans, report cards, and more.',
    landingEmailNotifications: 'Email Notifications',
    landingEmailNotificationsDesc: 'Send automatic reports to parents and administrators.',
    landingViewIntegrations: 'View all integrations',
    // Customization Section
    landingYourBrandYourWay: 'Your brand, your way',
    landingCustomizeDesc: 'Personalize everything with your school colors, logo, and preferences.',
    landingSchoolLogo: 'School Logo',
    landingSchoolLogoDesc: 'Add your logo to all documents and reports.',
    landingColorThemes: 'Color Themes',
    landingColorThemesDesc: 'Choose colors that match your school identity.',
    landingCustomTemplates: 'Custom Templates',
    landingCustomTemplatesDesc: 'Create reusable templates for your plans.',
    landingMultiLanguage: 'Multi-Language',
    landingMultiLanguageDesc: 'Work in English, Spanish, or both languages.',
    // Homeschool Section
    landingHomeschoolTitle: 'Homeschool Education',
    landingHomeschoolSubtitle: 'Your complete homeschool companion',
    landingHomeschoolDesc: 'Everything you need for a successful homeschool experience in one integrated platform.',
    landingAdaptiveLearning: 'Adaptive Learning',
    landingAdaptiveLearningDesc: 'Learning paths that adapt to each child\'s pace.',
    landingFullVisibility: 'Full Visibility',
    landingFullVisibilityDesc: 'Track progress in real-time with detailed reports.',
    landingFlexibleCurriculum: 'Flexible Curriculum',
    landingFlexibleCurriculumDesc: 'Customize the curriculum to fit your family\'s needs.',
    landing100Customizable: '100% Customizable',
    landingDownloadLearn: 'Download & Learn',
    landingDownloadLearnDesc: 'Export materials for offline learning.',
    landingPdfExportFeature: 'PDF Export',
    landingTextToSpeech: 'Text-to-Speech',
    landingTextToSpeechDesc: 'Audio support for all reading content.',
    landingAudioLearning: 'Audio Learning',
    landingSafeContent: 'Safe Content',
    landingSafeContentDesc: 'Age-appropriate and reviewed materials.',
    landingParentalControl: 'Parental Control',
    landingSubjectModules: 'Subject-Specific Modules',
    landingMathematics: 'Mathematics',
    landingLanguageArts: 'Language Arts',
    landingScience: 'Science',
    landingAstronomy: 'Astronomy',
    landingGeography: 'Geography',
    landingHistory: 'History',
    landingArt: 'Art',
    landingPhysicalEd: 'Physical Ed',
    landingStartHomeschooling: 'Start Homeschooling',
    // CTA Section
    landing7DaysFree: '7 days free',
    landingGetStartedToday: 'Get started today',
    landingStartYourJourney: 'Start your digital classroom journey. No credit card required.',
    landingNoCreditCard: 'No credit card required',
    landingSetup2Min: 'Setup in 2 minutes',
    landingCancelAnytime: 'Cancel anytime',
    landingSupportBilingual: 'Support in Spanish & English',
    landingActiveTeachers: 'active teachers',
    landingSignIn: 'Sign in',
    landingCreateAccountTab: 'Create account',
    landingContinueGoogle: 'Continue with Google',
    landingOrWithEmail: 'or with email',
    landingEmail: 'Email',
    landingPassword: 'Password',
    landingFullNameLabel: 'Full name',
    landingCreateFreeAccount: 'Create free account',
    // Footer
    landingContact: 'Contact',
    landingPrivacyPolicy: 'Privacy Policy',
    landingHelp: 'Help',
    landingTermsOfUse: 'Terms of Use',
    landingCookiesPolicy: 'Cookies Policy',
    landingAccessibility: 'Accessibility',
    landingAllRightsReserved: 'All rights reserved.'
  },
  es: {
    // Navigation
    dashboard: 'Panel',
    planner: 'Planificador',
    attendance: 'Asistencia',
    gradebook: 'Notas',
    classes: 'Clases',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    
    // Auth
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    name: 'Nombre',
    signInWithGoogle: 'Iniciar sesión con Google',
    orContinueWith: 'o continuar con',
    dontHaveAccount: '¿No tienes cuenta?',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    
    // Dashboard
    welcome: 'Bienvenido',
    todayOverview: 'Resumen de Hoy',
    quickActions: 'Acciones Rápidas',
    attendancePending: 'Asistencia Pendiente',
    upcomingAssignments: 'Próximas Tareas',
    recentPlans: 'Planes Recientes',
    totalClasses: 'Total de Clases',
    totalStudents: 'Total de Estudiantes',
    totalPlans: 'Total de Planes',
    
    // Classes
    addClass: 'Agregar Clase',
    className: 'Nombre de Clase',
    grade: 'Grado',
    section: 'Sección',
    subject: 'Materia',
    yearTerm: 'Año/Período',
    students: 'Estudiantes',
    addStudent: 'Agregar Estudiante',
    firstName: 'Nombre',
    lastName: 'Apellido',
    studentNumber: 'Número de Estudiante',
    parentEmail: 'Correo del Padre',
    notes: 'Notas',
    accommodations: 'Acomodaciones',
    
    // Planner
    weeklyPlan: 'Plan Semanal',
    createPlan: 'Crear Plan',
    weekOf: 'Semana del',
    unit: 'Unidad',
    story: 'Historia/Título',
    objectiveOfWeek: 'Objetivo de la Semana',
    skillsOfWeek: 'Destrezas de la Semana',
    dayTheme: 'Tema del Día',
    activities: 'Actividades',
    materials: 'Materiales',
    standards: 'Estándares',
    expectations: 'Expectativas',
    firstWeek: 'Primera Semana',
    secondWeek: 'Segunda Semana',
    saveAsTemplate: 'Guardar como Plantilla',
    duplicateLastWeek: 'Duplicar Última Semana',
    exportPdf: 'Exportar PDF',
    
    // Taxonomy levels
    level1Memory: 'Nivel 1: Memoria',
    level2Processing: 'Nivel 2: Procesamiento',
    level3Strategic: 'Nivel 3: Pensamiento Estratégico',
    level4Extended: 'Nivel 4: Pensamiento Extendido',
    
    // Activities
    brainstorming: 'Lluvia de Ideas',
    buildingBackground: 'Construir Conocimiento Previo',
    vocabularyDevelopment: 'Desarrollo de Vocabulario',
    readPages: 'Leer Páginas',
    guidedReading: 'Lectura Guiada y Coral',
    oralQuestions: 'Preguntas Orales',
    comprehensionQuestions: 'Preguntas de Comprensión',
    exercisePractice: 'Práctica de Ejercicios',
    other: 'Otro',
    
    // Materials
    book: 'Libro',
    notebook: 'Cuaderno',
    teachersGuide: 'Guía del Maestro',
    testQuiz: 'Prueba/Examen',
    dictionary: 'Diccionario',
    handouts: 'Hojas de Trabajo',
    
    // Standards domains
    listeningAndSpeaking: 'Escuchar/Hablar',
    foundationalSkills: 'Destrezas Fundamentales',
    reading: 'Lectura',
    writing: 'Escritura',
    language: 'Lenguaje',
    
    // Subject integration
    mathematics: 'Matemáticas',
    spanish: 'Español',
    socialStudies: 'Estudios Sociales',
    science: 'Ciencias',
    health: 'Salud',
    art: 'Arte',
    physicalEducation: 'Educación Física',
    religion: 'Religión',
    
    // Attendance
    takeAttendance: 'Tomar Asistencia',
    present: 'Presente',
    absent: 'Ausente',
    tardy: 'Tardanza',
    excused: 'Excusado',
    markAllPresent: 'Marcar Todos Presente',
    submitAttendance: 'Enviar Asistencia',
    attendanceReport: 'Reporte de Asistencia',
    
    // Gradebook
    assignments: 'Tareas',
    createAssignment: 'Crear Tarea',
    title: 'Título',
    description: 'Descripción',
    points: 'Puntos',
    dueDate: 'Fecha de Entrega',
    category: 'Categoría',
    homework: 'Tarea',
    quiz: 'Prueba Corta',
    test: 'Examen',
    project: 'Proyecto',
    gradeEntry: 'Entrada de Notas',
    missing: 'Falta',
    late: 'Tarde',
    
    // Common
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    view: 'Ver',
    search: 'Buscar',
    filter: 'Filtrar',
    loading: 'Cargando...',
    noData: 'No hay datos disponibles',
    confirmDelete: '¿Estás seguro de que deseas eliminar esto?',
    success: 'Éxito',
    error: 'Error',
    from: 'Desde',
    to: 'Hasta',
    date: 'Fecha',
    teacher: 'Maestro',
    selectLanguage: 'Seleccionar Idioma',
    
    // Days
    monday: 'Lunes',
    tuesday: 'Martes',
    wednesday: 'Miércoles',
    thursday: 'Jueves',
    friday: 'Viernes',
    
    // Games
    educationalGames: 'Juegos Educativos',
    myGames: 'Mis Juegos',
    createGame: 'Crear Juego',
    play: 'Jugar',
    copyLink: 'Copiar Enlace',
    shareToClassroom: 'Compartir en Classroom',
    deleteGame: 'Eliminar Juego',
    questions: 'Preguntas',
    gameType: 'Tipo de Juego',
    gradeLevel: 'Nivel de Grado',
    
    // Landing Page
    landingHeroTitle: 'Tu aula completa en una plataforma',
    landingHeroSubtitle: 'Planificación, asistencia, notas y asistente IA. Todo lo que un maestro necesita, en un solo lugar.',
    landingBuiltForTeachers: 'Diseñado para maestros',
    landingStartFree: 'Comenzar gratis',
    landingViewPricing: 'Ver precios',
    landingUsedBySchools: 'Usado por escuelas en Puerto Rico y más',
    landingEverythingYouNeed: 'Todo lo que necesitas',
    landingEverythingDesc: 'Una plataforma completa diseñada específicamente para maestros.',
    landingFeatures: 'Funciones',
    landingAiAssistant: 'Asistente IA',
    landingHomeschool: 'Educación en Casa',
    landingIntegrations: 'Integraciones',
    landingCustomization: 'Personalización',
    landingPricing: 'Precios',
    landingGetStarted: 'Comenzar - Iniciar sesión',
    landingStart: 'Comenzar',
    landingAiLessonPlan: 'Planificación IA',
    landingPresentations: 'Presentaciones',
    landingGrades: 'Calificaciones',
    landingPlanFaster: 'Planifica más rápido',
    landingPlanFasterDesc: 'Crea planes de lección semanales en segundos con nuestro formato intuitivo.',
    landingWeek1: 'Semana 1',
    landingYourBrand: 'Tu marca, tu estilo',
    landingYourBrandDesc: 'Personaliza con el logo y colores de tu escuela en todos los documentos.',
    landingYourSchool: 'Tu Escuela',
    landingCustomBranding: 'Marca personalizada',
    landingExportPro: 'Exporta profesionalmente',
    landingExportProDesc: 'Genera PDFs listos para imprimir: planes, boletas, paquetes para sustitutos.',
    landingDownloadPdf: 'Descargar PDF',
    landingAiAssistantTitle: 'Asistente de IA',
    landingAiAssistantDesc: 'Genera planes de lección, actividades, preguntas y más con IA.',
    landingLessonPlans: 'Planes de lección',
    landingQuizzesTests: 'Quizzes y exámenes',
    landingDigitalClassroom: 'Tu aula digital',
    landingTryFree: 'Prueba gratis por 30 días',
    landingNoCard: 'No requiere tarjeta de crédito',
    landingFullName: 'Nombre Completo',
    landingCreateAccount: 'Crear Cuenta Gratis',
    landingOrLoginWith: 'O inicia sesión con',
    landingHaveAccount: '¿Tienes cuenta?',
    landingLoginHere: 'Inicia sesión aquí',
    landingNeedAccount: '¿Necesitas cuenta?',
    landingRegisterHere: 'Regístrate aquí',
    // AI Section
    landingAiTeachingAssistant: 'Asistente de IA',
    landingYouAsked: 'Tú preguntaste:',
    landingAiResponse: 'Respuesta IA:',
    landingAiQuestion: '¿Cómo puedo enseñar fracciones equivalentes a 4to grado?',
    landingAiAnswer: 'Aquí tienes un plan de lección basado en el estándar CCSS.MATH.4.NF.A.1 con actividades manipulativas...',
    landingQuizzes: 'Quizzes',
    landingWorksheets: 'Hojas de Trabajo',
    landingIdeas: 'Ideas',
    landingNewAi: 'Nuevo: Inteligencia Artificial',
    landingAiAssistantToTeach: 'Tu asistente de IA para enseñar mejor',
    landingAiAssistantDesc2: 'Genera planes de lección, quizzes, resúmenes y actividades basadas en los estándares Common Core y Puerto Rico, al instante.',
    landingAlignedStandards: 'Alineado con Common Core y PR CORE',
    landingGenerateSeconds: 'Genera contenido en segundos',
    landingBilingual: 'Bilingüe: Español e Inglés',
    landingPoweredBy: 'Powered by Claude Sonnet 4.5',
    landingTryItFree: 'Probar gratis',
    landingIncludedSubscription: 'Incluido en suscripción',
    // Integrations Section
    landingConnectTools: 'Conecta con tus herramientas favoritas',
    landingConnectToolsDesc: 'Integra con las plataformas que ya usas para facilitar tu trabajo.',
    landingCalendarSync: 'Sincronización de Calendario',
    landingCalendarSyncDesc: 'Exporta tus planes a Google Calendar, Outlook o Apple Calendar.',
    landingGoogleClassroom: 'Google Classroom',
    landingGoogleClassroomDesc: 'Comparte actividades y juegos directamente con tus estudiantes.',
    landingPdfExport: 'Exportar PDF',
    landingPdfExportDesc: 'Genera PDFs profesionales para planes, boletas y más.',
    landingEmailNotifications: 'Notificaciones por Email',
    landingEmailNotificationsDesc: 'Envía reportes automáticos a padres y administradores.',
    landingViewIntegrations: 'Ver todas las integraciones',
    // Customization Section
    landingYourBrandYourWay: 'Tu marca, a tu manera',
    landingCustomizeDesc: 'Personaliza todo con los colores, logo y preferencias de tu escuela.',
    landingSchoolLogo: 'Logo de Escuela',
    landingSchoolLogoDesc: 'Añade tu logo a todos los documentos y reportes.',
    landingColorThemes: 'Temas de Color',
    landingColorThemesDesc: 'Elige colores que coincidan con la identidad de tu escuela.',
    landingCustomTemplates: 'Plantillas Personalizadas',
    landingCustomTemplatesDesc: 'Crea plantillas reutilizables para tus planes.',
    landingMultiLanguage: 'Multi-Idioma',
    landingMultiLanguageDesc: 'Trabaja en inglés, español o ambos idiomas.',
    // Homeschool Section
    landingHomeschoolTitle: 'Educación en Casa',
    landingHomeschoolSubtitle: 'Tu compañero completo de homeschool',
    landingHomeschoolDesc: 'Todo lo que necesitas para una experiencia exitosa de educación en casa en una plataforma integrada.',
    landingAdaptiveLearning: 'Aprendizaje Adaptativo',
    landingAdaptiveLearningDesc: 'Rutas de aprendizaje que se adaptan al ritmo de cada niño.',
    landingFullVisibility: 'Visibilidad Total',
    landingFullVisibilityDesc: 'Sigue el progreso en tiempo real con reportes detallados.',
    landingFlexibleCurriculum: 'Currículo Flexible',
    landingFlexibleCurriculumDesc: 'Personaliza el currículo según las necesidades de tu familia.',
    landing100Customizable: '100% Personalizable',
    landingDownloadLearn: 'Descarga y Aprende',
    landingDownloadLearnDesc: 'Exporta materiales para aprendizaje sin conexión.',
    landingPdfExportFeature: 'Exportar PDF',
    landingTextToSpeech: 'Texto a Voz',
    landingTextToSpeechDesc: 'Soporte de audio para todo el contenido de lectura.',
    landingAudioLearning: 'Aprendizaje Auditivo',
    landingSafeContent: 'Contenido Seguro',
    landingSafeContentDesc: 'Materiales apropiados para la edad y revisados.',
    landingParentalControl: 'Control Parental',
    landingSubjectModules: 'Módulos por Materia',
    landingMathematics: 'Matemáticas',
    landingLanguageArts: 'Lenguaje',
    landingScience: 'Ciencias',
    landingAstronomy: 'Astronomía',
    landingGeography: 'Geografía',
    landingHistory: 'Historia',
    landingArt: 'Arte',
    landingPhysicalEd: 'Educación Física',
    landingStartHomeschooling: 'Comenzar Educación en Casa',
    // CTA Section
    landing7DaysFree: '7 días gratis',
    landingGetStartedToday: 'Comienza hoy',
    landingStartYourJourney: 'Comienza tu viaje de aula digital. No requiere tarjeta de crédito.',
    landingNoCreditCard: 'Sin tarjeta de crédito requerida',
    landingSetup2Min: 'Configuración en 2 minutos',
    landingCancelAnytime: 'Cancela en cualquier momento',
    landingSupportBilingual: 'Soporte en español e inglés',
    landingActiveTeachers: 'maestros activos',
    landingSignIn: 'Iniciar sesión',
    landingCreateAccountTab: 'Crear cuenta',
    landingContinueGoogle: 'Continuar con Google',
    landingOrWithEmail: 'o con email',
    landingEmail: 'Correo electrónico',
    landingPassword: 'Contraseña',
    landingFullNameLabel: 'Nombre completo',
    landingCreateFreeAccount: 'Crear cuenta gratis',
    // Footer
    landingContact: 'Contacto',
    landingPrivacyPolicy: 'Política de Privacidad',
    landingHelp: 'Ayuda',
    landingTermsOfUse: 'Términos de Uso',
    landingCookiesPolicy: 'Política de Cookies',
    landingAccessibility: 'Accesibilidad',
    landingAllRightsReserved: 'Todos los derechos reservados.'
  },
  fr: {
    // Navigation
    dashboard: 'Tableau de Bord',
    planner: 'Planificateur',
    attendance: 'Présence',
    gradebook: 'Carnet de Notes',
    classes: 'Classes',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    
    // Auth
    login: 'Connexion',
    register: "S'inscrire",
    email: 'Email',
    password: 'Mot de Passe',
    name: 'Nom',
    signInWithGoogle: 'Se connecter avec Google',
    orContinueWith: 'ou continuer avec',
    dontHaveAccount: "Pas de compte?",
    alreadyHaveAccount: 'Déjà un compte?',
    
    // Dashboard
    welcome: 'Bienvenue',
    todayOverview: "Aperçu d'Aujourd'hui",
    quickActions: 'Actions Rapides',
    attendancePending: 'Présence en Attente',
    upcomingAssignments: 'Devoirs à Venir',
    recentPlans: 'Plans Récents',
    totalClasses: 'Total des Classes',
    totalStudents: 'Total des Élèves',
    totalPlans: 'Total des Plans',
    
    // Classes
    addClass: 'Ajouter Classe',
    className: 'Nom de Classe',
    grade: 'Niveau',
    section: 'Section',
    subject: 'Matière',
    yearTerm: 'Année/Période',
    students: 'Élèves',
    addStudent: 'Ajouter Élève',
    firstName: 'Prénom',
    lastName: 'Nom',
    studentNumber: "Numéro d'Élève",
    parentEmail: 'Email du Parent',
    notes: 'Notes',
    accommodations: 'Aménagements',
    
    // Planner
    weeklyPlan: 'Plan Hebdomadaire',
    createPlan: 'Créer Plan',
    weekOf: 'Semaine du',
    unit: 'Unité',
    story: 'Histoire/Titre',
    objectiveOfWeek: 'Objectif de la Semaine',
    skillsOfWeek: 'Compétences de la Semaine',
    dayTheme: 'Thème du Jour',
    activities: 'Activités',
    materials: 'Matériels',
    standards: 'Standards',
    expectations: 'Attentes',
    firstWeek: 'Première Semaine',
    secondWeek: 'Deuxième Semaine',
    saveAsTemplate: 'Enregistrer comme Modèle',
    duplicateLastWeek: 'Dupliquer Semaine Précédente',
    exportPdf: 'Exporter PDF',
    
    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    view: 'Voir',
    search: 'Rechercher',
    filter: 'Filtrer',
    loading: 'Chargement...',
    noData: 'Aucune donnée disponible',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer?',
    success: 'Succès',
    error: 'Erreur',
    from: 'De',
    to: 'À',
    date: 'Date',
    teacher: 'Enseignant',
    selectLanguage: 'Sélectionner la Langue',
    
    // Days
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    
    // Attendance
    takeAttendance: 'Prendre la Présence',
    present: 'Présent',
    absent: 'Absent',
    tardy: 'En Retard',
    excused: 'Excusé',
    markAllPresent: 'Marquer Tous Présents',
    submitAttendance: 'Soumettre Présence',
    
    // Gradebook
    assignments: 'Devoirs',
    createAssignment: 'Créer Devoir',
    title: 'Titre',
    description: 'Description',
    points: 'Points',
    dueDate: 'Date Limite',
    category: 'Catégorie',
    homework: 'Devoir',
    quiz: 'Quiz',
    test: 'Examen',
    project: 'Projet',
    
    // Games
    educationalGames: 'Jeux Éducatifs',
    myGames: 'Mes Jeux',
    createGame: 'Créer Jeu',
    play: 'Jouer',
    copyLink: 'Copier Lien',
    shareToClassroom: 'Partager sur Classroom',
    deleteGame: 'Supprimer Jeu',
    questions: 'Questions',
    gameType: 'Type de Jeu',
    gradeLevel: 'Niveau Scolaire',
    
    // Landing Page
    landingHeroTitle: 'Votre classe complète en une plateforme',
    landingHeroSubtitle: 'Planification, présence, notes et assistant IA. Tout ce dont un enseignant a besoin.',
    landingBuiltForTeachers: 'Conçu pour les enseignants',
    landingStartFree: 'Commencer gratuitement',
    landingViewPricing: 'Voir les tarifs',
    landingUsedBySchools: 'Utilisé par des écoles partout dans le monde',
    landingEverythingYouNeed: 'Tout ce dont vous avez besoin',
    landingEverythingDesc: 'Une plateforme complète conçue spécialement pour les enseignants.',
    landingFeatures: 'Fonctionnalités',
    landingAiAssistant: 'Assistant IA',
    landingHomeschool: 'École à la Maison',
    landingIntegrations: 'Intégrations',
    landingCustomization: 'Personnalisation',
    landingPricing: 'Tarifs',
    landingGetStarted: 'Commencer - Se Connecter',
    landingStart: 'Commencer',
    landingAiLessonPlan: 'Plan IA',
    landingPresentations: 'Présentations',
    landingGrades: 'Notes',
    landingPlanFaster: 'Planifiez plus vite',
    landingPlanFasterDesc: 'Créez des plans de cours hebdomadaires en quelques secondes.',
    landingWeek1: 'Semaine 1',
    landingYourBrand: 'Votre marque, votre style',
    landingYourBrandDesc: 'Personnalisez avec le logo et les couleurs de votre école.',
    landingYourSchool: 'Votre École',
    landingCustomBranding: 'Marque personnalisée',
    landingExportPro: 'Exportez professionnellement',
    landingExportProDesc: 'Générez des PDFs prêts à imprimer: plans, bulletins, dossiers.',
    landingDownloadPdf: 'Télécharger PDF',
    landingAiAssistantTitle: 'Assistant IA',
    landingAiAssistantDesc: 'Générez des plans de cours, activités et questions avec l\'IA.',
    landingLessonPlans: 'Plans de cours',
    landingQuizzesTests: 'Quiz et examens',
    landingDigitalClassroom: 'Votre classe numérique',
    landingTryFree: 'Essai gratuit de 30 jours',
    landingNoCard: 'Aucune carte de crédit requise',
    landingFullName: 'Nom Complet',
    landingCreateAccount: 'Créer un Compte Gratuit',
    landingOrLoginWith: 'Ou connectez-vous avec',
    landingHaveAccount: 'Avez-vous un compte?',
    landingLoginHere: 'Connectez-vous ici',
    landingNeedAccount: 'Besoin d\'un compte?',
    landingRegisterHere: 'Inscrivez-vous ici',
    // AI Section
    landingAiTeachingAssistant: 'Assistant IA pour l\'Enseignement',
    landingYouAsked: 'Vous avez demandé:',
    landingAiResponse: 'Réponse IA:',
    landingAiQuestion: 'Comment enseigner les fractions équivalentes en CM1?',
    landingAiAnswer: 'Voici un plan de cours basé sur les standards avec des activités pratiques...',
    landingQuizzes: 'Quiz',
    landingWorksheets: 'Fiches de travail',
    landingIdeas: 'Idées',
    landingNewAi: 'Nouveau: Intelligence Artificielle',
    landingAiAssistantToTeach: 'Votre assistant IA pour mieux enseigner',
    landingAiAssistantDesc2: 'Générez des plans de cours, quiz, résumés et activités basés sur les standards, instantanément.',
    landingAlignedStandards: 'Aligné avec les programmes officiels',
    landingGenerateSeconds: 'Générez du contenu en secondes',
    landingBilingual: 'Multilingue',
    landingPoweredBy: 'Propulsé par Claude Sonnet 4.5',
    landingTryItFree: 'Essayer gratuitement',
    landingIncludedSubscription: 'Inclus dans l\'abonnement',
    // Integrations Section
    landingConnectTools: 'Connectez vos outils favoris',
    landingConnectToolsDesc: 'Intégrez les plateformes que vous utilisez déjà.',
    landingCalendarSync: 'Sync Calendrier',
    landingCalendarSyncDesc: 'Exportez vos plans vers Google Calendar, Outlook ou Apple Calendar.',
    landingGoogleClassroom: 'Google Classroom',
    landingGoogleClassroomDesc: 'Partagez activités et jeux directement avec vos élèves.',
    landingPdfExport: 'Export PDF',
    landingPdfExportDesc: 'Générez des PDFs professionnels pour plans, bulletins et plus.',
    landingEmailNotifications: 'Notifications Email',
    landingEmailNotificationsDesc: 'Envoyez des rapports automatiques aux parents et administrateurs.',
    landingViewIntegrations: 'Voir toutes les intégrations',
    // Customization Section
    landingYourBrandYourWay: 'Votre marque, à votre façon',
    landingCustomizeDesc: 'Personnalisez tout avec les couleurs, logo et préférences de votre école.',
    landingSchoolLogo: 'Logo de l\'École',
    landingSchoolLogoDesc: 'Ajoutez votre logo à tous les documents et rapports.',
    landingColorThemes: 'Thèmes de Couleur',
    landingColorThemesDesc: 'Choisissez des couleurs qui correspondent à votre identité.',
    landingCustomTemplates: 'Modèles Personnalisés',
    landingCustomTemplatesDesc: 'Créez des modèles réutilisables pour vos plans.',
    landingMultiLanguage: 'Multi-Langue',
    landingMultiLanguageDesc: 'Travaillez en plusieurs langues.',
    // Homeschool Section
    landingHomeschoolTitle: 'École à la Maison',
    landingHomeschoolSubtitle: 'Votre compagnon complet pour l\'école à la maison',
    landingHomeschoolDesc: 'Tout ce dont vous avez besoin pour une expérience réussie d\'école à la maison.',
    landingAdaptiveLearning: 'Apprentissage Adaptatif',
    landingAdaptiveLearningDesc: 'Des parcours qui s\'adaptent au rythme de chaque enfant.',
    landingFullVisibility: 'Visibilité Totale',
    landingFullVisibilityDesc: 'Suivez les progrès en temps réel avec des rapports détaillés.',
    landingFlexibleCurriculum: 'Programme Flexible',
    landingFlexibleCurriculumDesc: 'Personnalisez le programme selon les besoins de votre famille.',
    landing100Customizable: '100% Personnalisable',
    landingDownloadLearn: 'Télécharger et Apprendre',
    landingDownloadLearnDesc: 'Exportez des matériaux pour l\'apprentissage hors ligne.',
    landingPdfExportFeature: 'Export PDF',
    landingTextToSpeech: 'Texte en Parole',
    landingTextToSpeechDesc: 'Support audio pour tout le contenu de lecture.',
    landingAudioLearning: 'Apprentissage Audio',
    landingSafeContent: 'Contenu Sécurisé',
    landingSafeContentDesc: 'Matériaux appropriés à l\'âge et vérifiés.',
    landingParentalControl: 'Contrôle Parental',
    landingSubjectModules: 'Modules par Matière',
    landingMathematics: 'Mathématiques',
    landingLanguageArts: 'Français',
    landingScience: 'Sciences',
    landingAstronomy: 'Astronomie',
    landingGeography: 'Géographie',
    landingHistory: 'Histoire',
    landingArt: 'Art',
    landingPhysicalEd: 'Éducation Physique',
    landingStartHomeschooling: 'Commencer l\'École à la Maison',
    // CTA Section
    landing7DaysFree: '7 jours gratuits',
    landingGetStartedToday: 'Commencez aujourd\'hui',
    landingStartYourJourney: 'Commencez votre parcours de classe numérique. Sans carte de crédit.',
    landingNoCreditCard: 'Sans carte de crédit requise',
    landingSetup2Min: 'Configuration en 2 minutes',
    landingCancelAnytime: 'Annulez à tout moment',
    landingSupportBilingual: 'Support multilingue',
    landingActiveTeachers: 'enseignants actifs',
    landingSignIn: 'Se connecter',
    landingCreateAccountTab: 'Créer un compte',
    landingContinueGoogle: 'Continuer avec Google',
    landingOrWithEmail: 'ou avec email',
    landingEmail: 'Email',
    landingPassword: 'Mot de passe',
    landingFullNameLabel: 'Nom complet',
    landingCreateFreeAccount: 'Créer un compte gratuit',
    // Footer
    landingContact: 'Contact',
    landingPrivacyPolicy: 'Politique de Confidentialité',
    landingHelp: 'Aide',
    landingTermsOfUse: 'Conditions d\'Utilisation',
    landingCookiesPolicy: 'Politique des Cookies',
    landingAccessibility: 'Accessibilité',
    landingAllRightsReserved: 'Tous droits réservés.'
  },
  pt: {
    // Navigation
    dashboard: 'Painel',
    planner: 'Planejador',
    attendance: 'Presença',
    gradebook: 'Boletim',
    classes: 'Turmas',
    settings: 'Configurações',
    logout: 'Sair',
    
    // Auth
    login: 'Entrar',
    register: 'Cadastrar',
    email: 'Email',
    password: 'Senha',
    name: 'Nome',
    signInWithGoogle: 'Entrar com Google',
    orContinueWith: 'ou continuar com',
    dontHaveAccount: 'Não tem conta?',
    alreadyHaveAccount: 'Já tem conta?',
    
    // Dashboard
    welcome: 'Bem-vindo',
    todayOverview: 'Resumo de Hoje',
    quickActions: 'Ações Rápidas',
    attendancePending: 'Presença Pendente',
    upcomingAssignments: 'Próximas Tarefas',
    recentPlans: 'Planos Recentes',
    totalClasses: 'Total de Turmas',
    totalStudents: 'Total de Alunos',
    totalPlans: 'Total de Planos',
    
    // Classes
    addClass: 'Adicionar Turma',
    className: 'Nome da Turma',
    grade: 'Série',
    section: 'Seção',
    subject: 'Matéria',
    yearTerm: 'Ano/Período',
    students: 'Alunos',
    addStudent: 'Adicionar Aluno',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    studentNumber: 'Número do Aluno',
    parentEmail: 'Email do Responsável',
    notes: 'Notas',
    accommodations: 'Adaptações',
    
    // Common
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    view: 'Ver',
    search: 'Buscar',
    filter: 'Filtrar',
    loading: 'Carregando...',
    noData: 'Nenhum dado disponível',
    confirmDelete: 'Tem certeza que deseja excluir?',
    success: 'Sucesso',
    error: 'Erro',
    from: 'De',
    to: 'Até',
    date: 'Data',
    teacher: 'Professor',
    selectLanguage: 'Selecionar Idioma',
    
    // Days
    monday: 'Segunda',
    tuesday: 'Terça',
    wednesday: 'Quarta',
    thursday: 'Quinta',
    friday: 'Sexta',
    
    // Games
    educationalGames: 'Jogos Educativos',
    myGames: 'Meus Jogos',
    createGame: 'Criar Jogo',
    play: 'Jogar',
    copyLink: 'Copiar Link',
    shareToClassroom: 'Compartilhar no Classroom',
    deleteGame: 'Excluir Jogo',
    questions: 'Perguntas',
    gameType: 'Tipo de Jogo',
    gradeLevel: 'Nível Escolar',
    
    // Landing Page
    landingHeroTitle: 'Sua sala de aula completa em uma plataforma',
    landingHeroSubtitle: 'Planejamento, presença, notas e assistente IA. Tudo o que um professor precisa.',
    landingBuiltForTeachers: 'Feito para professores',
    landingStartFree: 'Começar grátis',
    landingViewPricing: 'Ver preços',
    landingUsedBySchools: 'Usado por escolas em todo o mundo',
    landingEverythingYouNeed: 'Tudo o que você precisa',
    landingEverythingDesc: 'Uma plataforma completa projetada especialmente para professores.',
    landingFeatures: 'Recursos',
    landingAiAssistant: 'Assistente IA',
    landingHomeschool: 'Ensino em Casa',
    landingIntegrations: 'Integrações',
    landingCustomization: 'Personalização',
    landingPricing: 'Preços',
    landingGetStarted: 'Começar - Entrar',
    landingStart: 'Começar',
    landingAiLessonPlan: 'Plano IA',
    landingPresentations: 'Apresentações',
    landingGrades: 'Notas',
    landingPlanFaster: 'Planeje mais rápido',
    landingPlanFasterDesc: 'Crie planos de aula semanais em segundos com nosso formato intuitivo.',
    landingWeek1: 'Semana 1',
    landingYourBrand: 'Sua marca, seu estilo',
    landingYourBrandDesc: 'Personalize com o logo e as cores da sua escola.',
    landingYourSchool: 'Sua Escola',
    landingCustomBranding: 'Marca personalizada',
    landingExportPro: 'Exporte profissionalmente',
    landingExportProDesc: 'Gere PDFs prontos para imprimir: planos, boletins, pacotes.',
    landingDownloadPdf: 'Baixar PDF',
    landingAiAssistantTitle: 'Assistente IA',
    landingAiAssistantDesc: 'Gere planos de aula, atividades e perguntas com IA.',
    landingLessonPlans: 'Planos de aula',
    landingQuizzesTests: 'Quizzes e provas',
    landingDigitalClassroom: 'Sua sala de aula digital',
    landingTryFree: 'Teste grátis por 30 dias',
    landingNoCard: 'Não requer cartão de crédito',
    landingFullName: 'Nome Completo',
    landingCreateAccount: 'Criar Conta Grátis',
    landingOrLoginWith: 'Ou entre com',
    landingHaveAccount: 'Tem uma conta?',
    landingLoginHere: 'Entre aqui',
    landingNeedAccount: 'Precisa de conta?',
    landingRegisterHere: 'Cadastre-se aqui',
    // AI Section
    landingAiTeachingAssistant: 'Assistente IA para Ensino',
    landingYouAsked: 'Você perguntou:',
    landingAiResponse: 'Resposta IA:',
    landingAiQuestion: 'Como posso ensinar frações equivalentes para o 4º ano?',
    landingAiAnswer: 'Aqui está um plano de aula baseado nos padrões com atividades práticas...',
    landingQuizzes: 'Quizzes',
    landingWorksheets: 'Folhas de Exercícios',
    landingIdeas: 'Ideias',
    landingNewAi: 'Novo: Inteligência Artificial',
    landingAiAssistantToTeach: 'Seu assistente IA para ensinar melhor',
    landingAiAssistantDesc2: 'Gere planos de aula, quizzes, resumos e atividades baseadas nos padrões, instantaneamente.',
    landingAlignedStandards: 'Alinhado com os padrões curriculares',
    landingGenerateSeconds: 'Gere conteúdo em segundos',
    landingBilingual: 'Multilíngue',
    landingPoweredBy: 'Desenvolvido com Claude Sonnet 4.5',
    landingTryItFree: 'Testar grátis',
    landingIncludedSubscription: 'Incluído na assinatura',
    // Integrations Section
    landingConnectTools: 'Conecte suas ferramentas favoritas',
    landingConnectToolsDesc: 'Integre as plataformas que você já usa.',
    landingCalendarSync: 'Sincronização de Calendário',
    landingCalendarSyncDesc: 'Exporte seus planos para Google Calendar, Outlook ou Apple Calendar.',
    landingGoogleClassroom: 'Google Classroom',
    landingGoogleClassroomDesc: 'Compartilhe atividades e jogos diretamente com seus alunos.',
    landingPdfExport: 'Exportar PDF',
    landingPdfExportDesc: 'Gere PDFs profissionais para planos, boletins e mais.',
    landingEmailNotifications: 'Notificações por Email',
    landingEmailNotificationsDesc: 'Envie relatórios automáticos para pais e administradores.',
    landingViewIntegrations: 'Ver todas as integrações',
    // Customization Section
    landingYourBrandYourWay: 'Sua marca, do seu jeito',
    landingCustomizeDesc: 'Personalize tudo com as cores, logo e preferências da sua escola.',
    landingSchoolLogo: 'Logo da Escola',
    landingSchoolLogoDesc: 'Adicione seu logo a todos os documentos e relatórios.',
    landingColorThemes: 'Temas de Cores',
    landingColorThemesDesc: 'Escolha cores que combinem com a identidade da sua escola.',
    landingCustomTemplates: 'Modelos Personalizados',
    landingCustomTemplatesDesc: 'Crie modelos reutilizáveis para seus planos.',
    landingMultiLanguage: 'Multi-Idioma',
    landingMultiLanguageDesc: 'Trabalhe em vários idiomas.',
    // Homeschool Section
    landingHomeschoolTitle: 'Ensino em Casa',
    landingHomeschoolSubtitle: 'Seu companheiro completo para homeschool',
    landingHomeschoolDesc: 'Tudo o que você precisa para uma experiência de ensino em casa bem-sucedida.',
    landingAdaptiveLearning: 'Aprendizado Adaptativo',
    landingAdaptiveLearningDesc: 'Caminhos de aprendizado que se adaptam ao ritmo de cada criança.',
    landingFullVisibility: 'Visibilidade Total',
    landingFullVisibilityDesc: 'Acompanhe o progresso em tempo real com relatórios detalhados.',
    landingFlexibleCurriculum: 'Currículo Flexível',
    landingFlexibleCurriculumDesc: 'Personalize o currículo de acordo com as necessidades da sua família.',
    landing100Customizable: '100% Personalizável',
    landingDownloadLearn: 'Baixar e Aprender',
    landingDownloadLearnDesc: 'Exporte materiais para aprendizado offline.',
    landingPdfExportFeature: 'Exportar PDF',
    landingTextToSpeech: 'Texto para Fala',
    landingTextToSpeechDesc: 'Suporte de áudio para todo o conteúdo de leitura.',
    landingAudioLearning: 'Aprendizado por Áudio',
    landingSafeContent: 'Conteúdo Seguro',
    landingSafeContentDesc: 'Materiais apropriados para a idade e revisados.',
    landingParentalControl: 'Controle Parental',
    landingSubjectModules: 'Módulos por Matéria',
    landingMathematics: 'Matemática',
    landingLanguageArts: 'Português',
    landingScience: 'Ciências',
    landingAstronomy: 'Astronomia',
    landingGeography: 'Geografia',
    landingHistory: 'História',
    landingArt: 'Arte',
    landingPhysicalEd: 'Educação Física',
    landingStartHomeschooling: 'Começar Ensino em Casa',
    // CTA Section
    landing7DaysFree: '7 dias grátis',
    landingGetStartedToday: 'Comece hoje',
    landingStartYourJourney: 'Comece sua jornada de sala de aula digital. Sem cartão de crédito.',
    landingNoCreditCard: 'Sem cartão de crédito necessário',
    landingSetup2Min: 'Configuração em 2 minutos',
    landingCancelAnytime: 'Cancele a qualquer momento',
    landingSupportBilingual: 'Suporte multilíngue',
    landingActiveTeachers: 'professores ativos',
    landingSignIn: 'Entrar',
    landingCreateAccountTab: 'Criar conta',
    landingContinueGoogle: 'Continuar com Google',
    landingOrWithEmail: 'ou com email',
    landingEmail: 'Email',
    landingPassword: 'Senha',
    landingFullNameLabel: 'Nome completo',
    landingCreateFreeAccount: 'Criar conta grátis',
    // Footer
    landingContact: 'Contato',
    landingPrivacyPolicy: 'Política de Privacidade',
    landingHelp: 'Ajuda',
    landingTermsOfUse: 'Termos de Uso',
    landingCookiesPolicy: 'Política de Cookies',
    landingAccessibility: 'Acessibilidade',
    landingAllRightsReserved: 'Todos os direitos reservados.'
  },
  de: {
    // Navigation
    dashboard: 'Übersicht',
    planner: 'Unterrichtsplaner',
    attendance: 'Anwesenheit',
    gradebook: 'Notenbuch',
    classes: 'Klassen',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    
    // Auth
    login: 'Anmelden',
    register: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    name: 'Name',
    signInWithGoogle: 'Mit Google anmelden',
    orContinueWith: 'oder weiter mit',
    dontHaveAccount: 'Kein Konto?',
    alreadyHaveAccount: 'Bereits ein Konto?',
    
    // Dashboard
    welcome: 'Willkommen',
    todayOverview: 'Heutige Übersicht',
    quickActions: 'Schnellaktionen',
    attendancePending: 'Anwesenheit ausstehend',
    upcomingAssignments: 'Anstehende Aufgaben',
    recentPlans: 'Aktuelle Pläne',
    totalClasses: 'Gesamtklassen',
    totalStudents: 'Gesamtschüler',
    totalPlans: 'Gesamtpläne',
    
    // Classes
    addClass: 'Klasse hinzufügen',
    className: 'Klassenname',
    grade: 'Klassenstufe',
    section: 'Abschnitt',
    subject: 'Fach',
    yearTerm: 'Jahr/Semester',
    students: 'Schüler',
    addStudent: 'Schüler hinzufügen',
    firstName: 'Vorname',
    lastName: 'Nachname',
    studentNumber: 'Schülernummer',
    parentEmail: 'Eltern-E-Mail',
    notes: 'Notizen',
    accommodations: 'Anpassungen',
    
    // Common
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    view: 'Ansehen',
    search: 'Suchen',
    filter: 'Filtern',
    loading: 'Laden...',
    noData: 'Keine Daten verfügbar',
    confirmDelete: 'Möchten Sie dies wirklich löschen?',
    success: 'Erfolg',
    error: 'Fehler',
    from: 'Von',
    to: 'Bis',
    date: 'Datum',
    teacher: 'Lehrer',
    selectLanguage: 'Sprache auswählen',
    
    // Days
    monday: 'Montag',
    tuesday: 'Dienstag',
    wednesday: 'Mittwoch',
    thursday: 'Donnerstag',
    friday: 'Freitag',
    
    // Games
    educationalGames: 'Lernspiele',
    myGames: 'Meine Spiele',
    createGame: 'Spiel erstellen',
    play: 'Spielen',
    copyLink: 'Link kopieren',
    shareToClassroom: 'Im Classroom teilen',
    deleteGame: 'Spiel löschen',
    questions: 'Fragen',
    gameType: 'Spieltyp',
    gradeLevel: 'Klassenstufe',
    
    // Landing Page
    landingHeroTitle: 'Ihr komplettes Klassenzimmer in einer Plattform',
    landingHeroSubtitle: 'Unterrichtsplanung, Anwesenheit, Noten und KI-Assistent. Alles was ein Lehrer braucht.',
    landingBuiltForTeachers: 'Entwickelt für Lehrer',
    landingStartFree: 'Kostenlos starten',
    landingViewPricing: 'Preise ansehen',
    landingUsedBySchools: 'Genutzt von Schulen weltweit',
    landingEverythingYouNeed: 'Alles was Sie brauchen',
    landingEverythingDesc: 'Eine komplette Plattform speziell für Lehrer entwickelt.',
    landingFeatures: 'Funktionen',
    landingAiAssistant: 'KI-Assistent',
    landingHomeschool: 'Heimunterricht',
    landingIntegrations: 'Integrationen',
    landingCustomization: 'Anpassung',
    landingPricing: 'Preise',
    landingGetStarted: 'Starten - Anmelden',
    landingStart: 'Starten',
    landingAiLessonPlan: 'KI-Plan',
    landingPresentations: 'Präsentationen',
    landingGrades: 'Noten',
    landingPlanFaster: 'Schneller planen',
    landingPlanFasterDesc: 'Erstellen Sie wöchentliche Unterrichtspläne in Sekunden.',
    landingWeek1: 'Woche 1',
    landingYourBrand: 'Ihre Marke, Ihr Stil',
    landingYourBrandDesc: 'Personalisieren Sie mit dem Logo und den Farben Ihrer Schule.',
    landingYourSchool: 'Ihre Schule',
    landingCustomBranding: 'Eigenes Branding',
    landingExportPro: 'Professionell exportieren',
    landingExportProDesc: 'Erstellen Sie druckfertige PDFs: Pläne, Zeugnisse, Vertretungsmappen.',
    landingDownloadPdf: 'PDF herunterladen',
    landingAiAssistantTitle: 'KI-Assistent',
    landingAiAssistantDesc: 'Erstellen Sie Unterrichtspläne, Aktivitäten und Fragen mit KI.',
    landingLessonPlans: 'Unterrichtspläne',
    landingQuizzesTests: 'Quiz und Tests',
    landingDigitalClassroom: 'Ihr digitales Klassenzimmer',
    landingTryFree: '30 Tage kostenlos testen',
    landingNoCard: 'Keine Kreditkarte erforderlich',
    landingFullName: 'Vollständiger Name',
    landingCreateAccount: 'Kostenloses Konto erstellen',
    landingOrLoginWith: 'Oder anmelden mit',
    landingHaveAccount: 'Haben Sie ein Konto?',
    landingLoginHere: 'Hier anmelden',
    landingNeedAccount: 'Brauchen Sie ein Konto?',
    landingRegisterHere: 'Hier registrieren',
    // AI Section
    landingAiTeachingAssistant: 'KI-Unterrichtsassistent',
    landingYouAsked: 'Sie fragten:',
    landingAiResponse: 'KI-Antwort:',
    landingAiQuestion: 'Wie kann ich äquivalente Brüche in der 4. Klasse unterrichten?',
    landingAiAnswer: 'Hier ist ein Unterrichtsplan basierend auf Standards mit praktischen Aktivitäten...',
    landingQuizzes: 'Quiz',
    landingWorksheets: 'Arbeitsblätter',
    landingIdeas: 'Ideen',
    landingNewAi: 'Neu: Künstliche Intelligenz',
    landingAiAssistantToTeach: 'Ihr KI-Assistent für besseren Unterricht',
    landingAiAssistantDesc2: 'Erstellen Sie Unterrichtspläne, Quiz, Zusammenfassungen und Aktivitäten basierend auf Standards, sofort.',
    landingAlignedStandards: 'Ausgerichtet an Bildungsstandards',
    landingGenerateSeconds: 'Inhalte in Sekunden erstellen',
    landingBilingual: 'Mehrsprachig',
    landingPoweredBy: 'Betrieben von Claude Sonnet 4.5',
    landingTryItFree: 'Kostenlos testen',
    landingIncludedSubscription: 'Im Abonnement enthalten',
    // Integrations Section
    landingConnectTools: 'Verbinden Sie Ihre Lieblingswerkzeuge',
    landingConnectToolsDesc: 'Integrieren Sie Plattformen, die Sie bereits nutzen.',
    landingCalendarSync: 'Kalender-Sync',
    landingCalendarSyncDesc: 'Exportieren Sie Ihre Pläne zu Google Calendar, Outlook oder Apple Calendar.',
    landingGoogleClassroom: 'Google Classroom',
    landingGoogleClassroomDesc: 'Teilen Sie Aktivitäten und Spiele direkt mit Ihren Schülern.',
    landingPdfExport: 'PDF-Export',
    landingPdfExportDesc: 'Erstellen Sie professionelle PDFs für Pläne, Zeugnisse und mehr.',
    landingEmailNotifications: 'E-Mail-Benachrichtigungen',
    landingEmailNotificationsDesc: 'Senden Sie automatische Berichte an Eltern und Administratoren.',
    landingViewIntegrations: 'Alle Integrationen ansehen',
    // Customization Section
    landingYourBrandYourWay: 'Ihre Marke, auf Ihre Art',
    landingCustomizeDesc: 'Personalisieren Sie alles mit den Farben, dem Logo und den Präferenzen Ihrer Schule.',
    landingSchoolLogo: 'Schullogo',
    landingSchoolLogoDesc: 'Fügen Sie Ihr Logo zu allen Dokumenten und Berichten hinzu.',
    landingColorThemes: 'Farbthemen',
    landingColorThemesDesc: 'Wählen Sie Farben, die zu Ihrer Schulidentität passen.',
    landingCustomTemplates: 'Benutzerdefinierte Vorlagen',
    landingCustomTemplatesDesc: 'Erstellen Sie wiederverwendbare Vorlagen für Ihre Pläne.',
    landingMultiLanguage: 'Mehrsprachig',
    landingMultiLanguageDesc: 'Arbeiten Sie in mehreren Sprachen.',
    // Homeschool Section
    landingHomeschoolTitle: 'Heimunterricht',
    landingHomeschoolSubtitle: 'Ihr kompletter Heimunterricht-Begleiter',
    landingHomeschoolDesc: 'Alles, was Sie für eine erfolgreiche Heimunterricht-Erfahrung brauchen.',
    landingAdaptiveLearning: 'Adaptives Lernen',
    landingAdaptiveLearningDesc: 'Lernpfade, die sich an das Tempo jedes Kindes anpassen.',
    landingFullVisibility: 'Volle Sichtbarkeit',
    landingFullVisibilityDesc: 'Verfolgen Sie den Fortschritt in Echtzeit mit detaillierten Berichten.',
    landingFlexibleCurriculum: 'Flexibler Lehrplan',
    landingFlexibleCurriculumDesc: 'Passen Sie den Lehrplan an die Bedürfnisse Ihrer Familie an.',
    landing100Customizable: '100% Anpassbar',
    landingDownloadLearn: 'Herunterladen und Lernen',
    landingDownloadLearnDesc: 'Exportieren Sie Materialien für Offline-Lernen.',
    landingPdfExportFeature: 'PDF-Export',
    landingTextToSpeech: 'Text-zu-Sprache',
    landingTextToSpeechDesc: 'Audio-Unterstützung für alle Leseinhalte.',
    landingAudioLearning: 'Audio-Lernen',
    landingSafeContent: 'Sicherer Inhalt',
    landingSafeContentDesc: 'Altersgerechte und geprüfte Materialien.',
    landingParentalControl: 'Elternkontrolle',
    landingSubjectModules: 'Fachmodule',
    landingMathematics: 'Mathematik',
    landingLanguageArts: 'Deutsch',
    landingScience: 'Naturwissenschaften',
    landingAstronomy: 'Astronomie',
    landingGeography: 'Geographie',
    landingHistory: 'Geschichte',
    landingArt: 'Kunst',
    landingPhysicalEd: 'Sport',
    landingStartHomeschooling: 'Heimunterricht starten',
    // CTA Section
    landing7DaysFree: '7 Tage kostenlos',
    landingGetStartedToday: 'Starten Sie heute',
    landingStartYourJourney: 'Starten Sie Ihre digitale Klassenzimmer-Reise. Keine Kreditkarte erforderlich.',
    landingNoCreditCard: 'Keine Kreditkarte erforderlich',
    landingSetup2Min: 'Einrichtung in 2 Minuten',
    landingCancelAnytime: 'Jederzeit kündbar',
    landingSupportBilingual: 'Mehrsprachiger Support',
    landingActiveTeachers: 'aktive Lehrer',
    landingSignIn: 'Anmelden',
    landingCreateAccountTab: 'Konto erstellen',
    landingContinueGoogle: 'Mit Google fortfahren',
    landingOrWithEmail: 'oder mit E-Mail',
    landingEmail: 'E-Mail',
    landingPassword: 'Passwort',
    landingFullNameLabel: 'Vollständiger Name',
    landingCreateFreeAccount: 'Kostenloses Konto erstellen',
    // Footer
    landingContact: 'Kontakt',
    landingPrivacyPolicy: 'Datenschutzrichtlinie',
    landingHelp: 'Hilfe',
    landingTermsOfUse: 'Nutzungsbedingungen',
    landingCookiesPolicy: 'Cookie-Richtlinie',
    landingAccessibility: 'Barrierefreiheit',
    landingAllRightsReserved: 'Alle Rechte vorbehalten.'
  },
  it: {
    // Navigation
    dashboard: 'Pannello',
    planner: 'Pianificatore',
    attendance: 'Presenze',
    gradebook: 'Registro Voti',
    classes: 'Classi',
    settings: 'Impostazioni',
    logout: 'Esci',
    
    // Auth
    login: 'Accedi',
    register: 'Registrati',
    email: 'Email',
    password: 'Password',
    name: 'Nome',
    signInWithGoogle: 'Accedi con Google',
    orContinueWith: 'o continua con',
    dontHaveAccount: 'Non hai un account?',
    alreadyHaveAccount: 'Hai già un account?',
    
    // Dashboard
    welcome: 'Benvenuto',
    todayOverview: 'Panoramica di Oggi',
    quickActions: 'Azioni Rapide',
    attendancePending: 'Presenze in Sospeso',
    upcomingAssignments: 'Compiti in Arrivo',
    recentPlans: 'Piani Recenti',
    totalClasses: 'Totale Classi',
    totalStudents: 'Totale Studenti',
    totalPlans: 'Totale Piani',
    
    // Classes
    addClass: 'Aggiungi Classe',
    className: 'Nome Classe',
    grade: 'Anno',
    section: 'Sezione',
    subject: 'Materia',
    yearTerm: 'Anno/Periodo',
    students: 'Studenti',
    addStudent: 'Aggiungi Studente',
    firstName: 'Nome',
    lastName: 'Cognome',
    studentNumber: 'Numero Studente',
    parentEmail: 'Email Genitore',
    notes: 'Note',
    accommodations: 'Adattamenti',
    
    // Common
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    edit: 'Modifica',
    view: 'Visualizza',
    search: 'Cerca',
    filter: 'Filtra',
    loading: 'Caricamento...',
    noData: 'Nessun dato disponibile',
    confirmDelete: 'Sei sicuro di voler eliminare?',
    success: 'Successo',
    error: 'Errore',
    from: 'Da',
    to: 'A',
    date: 'Data',
    teacher: 'Insegnante',
    selectLanguage: 'Seleziona Lingua',
    
    // Days
    monday: 'Lunedì',
    tuesday: 'Martedì',
    wednesday: 'Mercoledì',
    thursday: 'Giovedì',
    friday: 'Venerdì',
    
    // Games
    educationalGames: 'Giochi Educativi',
    myGames: 'I Miei Giochi',
    createGame: 'Crea Gioco',
    play: 'Gioca',
    copyLink: 'Copia Link',
    shareToClassroom: 'Condividi su Classroom',
    deleteGame: 'Elimina Gioco',
    questions: 'Domande',
    gameType: 'Tipo di Gioco',
    gradeLevel: 'Livello Scolastico',
    
    // Landing Page
    landingHeroTitle: 'La tua classe completa in una piattaforma',
    landingHeroSubtitle: 'Pianificazione, presenze, voti e assistente IA. Tutto ciò di cui un insegnante ha bisogno.',
    landingBuiltForTeachers: 'Progettato per insegnanti',
    landingStartFree: 'Inizia gratis',
    landingViewPricing: 'Vedi prezzi',
    landingUsedBySchools: 'Usato da scuole in tutto il mondo',
    landingEverythingYouNeed: 'Tutto ciò di cui hai bisogno',
    landingEverythingDesc: 'Una piattaforma completa progettata appositamente per gli insegnanti.',
    landingFeatures: 'Funzionalità',
    landingAiAssistant: 'Assistente IA',
    landingHomeschool: 'Homeschooling',
    landingIntegrations: 'Integrazioni',
    landingCustomization: 'Personalizzazione',
    landingPricing: 'Prezzi',
    landingGetStarted: 'Inizia - Accedi',
    landingStart: 'Inizia',
    landingAiLessonPlan: 'Piano IA',
    landingPresentations: 'Presentazioni',
    landingGrades: 'Voti',
    landingPlanFaster: 'Pianifica più veloce',
    landingPlanFasterDesc: 'Crea piani di lezione settimanali in pochi secondi.',
    landingWeek1: 'Settimana 1',
    landingYourBrand: 'Il tuo marchio, il tuo stile',
    landingYourBrandDesc: 'Personalizza con il logo e i colori della tua scuola.',
    landingYourSchool: 'La Tua Scuola',
    landingCustomBranding: 'Marchio personalizzato',
    landingExportPro: 'Esporta professionalmente',
    landingExportProDesc: 'Genera PDF pronti per la stampa: piani, pagelle, dossier.',
    landingDownloadPdf: 'Scarica PDF',
    landingAiAssistantTitle: 'Assistente IA',
    landingAiAssistantDesc: 'Genera piani di lezione, attività e domande con l\'IA.',
    landingLessonPlans: 'Piani di lezione',
    landingQuizzesTests: 'Quiz e test',
    landingDigitalClassroom: 'La tua classe digitale',
    landingTryFree: 'Prova gratuita di 30 giorni',
    landingNoCard: 'Nessuna carta di credito richiesta',
    landingFullName: 'Nome Completo',
    landingCreateAccount: 'Crea Account Gratuito',
    landingOrLoginWith: 'O accedi con',
    landingHaveAccount: 'Hai un account?',
    landingLoginHere: 'Accedi qui',
    landingNeedAccount: 'Hai bisogno di un account?',
    landingRegisterHere: 'Registrati qui',
    // AI Section
    landingAiTeachingAssistant: 'Assistente IA per l\'Insegnamento',
    landingYouAsked: 'Hai chiesto:',
    landingAiResponse: 'Risposta IA:',
    landingAiQuestion: 'Come posso insegnare le frazioni equivalenti alla 4a classe?',
    landingAiAnswer: 'Ecco un piano di lezione basato sugli standard con attività pratiche...',
    landingQuizzes: 'Quiz',
    landingWorksheets: 'Schede di Lavoro',
    landingIdeas: 'Idee',
    landingNewAi: 'Nuovo: Intelligenza Artificiale',
    landingAiAssistantToTeach: 'Il tuo assistente IA per insegnare meglio',
    landingAiAssistantDesc2: 'Genera piani di lezione, quiz, riassunti e attività basate sugli standard, istantaneamente.',
    landingAlignedStandards: 'Allineato agli standard educativi',
    landingGenerateSeconds: 'Genera contenuti in secondi',
    landingBilingual: 'Multilingue',
    landingPoweredBy: 'Alimentato da Claude Sonnet 4.5',
    landingTryItFree: 'Prova gratis',
    landingIncludedSubscription: 'Incluso nell\'abbonamento',
    // Integrations Section
    landingConnectTools: 'Connetti i tuoi strumenti preferiti',
    landingConnectToolsDesc: 'Integra le piattaforme che già usi.',
    landingCalendarSync: 'Sincronizzazione Calendario',
    landingCalendarSyncDesc: 'Esporta i tuoi piani su Google Calendar, Outlook o Apple Calendar.',
    landingGoogleClassroom: 'Google Classroom',
    landingGoogleClassroomDesc: 'Condividi attività e giochi direttamente con i tuoi studenti.',
    landingPdfExport: 'Esporta PDF',
    landingPdfExportDesc: 'Genera PDF professionali per piani, pagelle e altro.',
    landingEmailNotifications: 'Notifiche Email',
    landingEmailNotificationsDesc: 'Invia rapporti automatici a genitori e amministratori.',
    landingViewIntegrations: 'Vedi tutte le integrazioni',
    // Customization Section
    landingYourBrandYourWay: 'Il tuo marchio, a modo tuo',
    landingCustomizeDesc: 'Personalizza tutto con colori, logo e preferenze della tua scuola.',
    landingSchoolLogo: 'Logo della Scuola',
    landingSchoolLogoDesc: 'Aggiungi il tuo logo a tutti i documenti e rapporti.',
    landingColorThemes: 'Temi di Colore',
    landingColorThemesDesc: 'Scegli colori che corrispondono all\'identità della tua scuola.',
    landingCustomTemplates: 'Modelli Personalizzati',
    landingCustomTemplatesDesc: 'Crea modelli riutilizzabili per i tuoi piani.',
    landingMultiLanguage: 'Multi-Lingua',
    landingMultiLanguageDesc: 'Lavora in più lingue.',
    // Homeschool Section
    landingHomeschoolTitle: 'Homeschooling',
    landingHomeschoolSubtitle: 'Il tuo compagno completo per l\'homeschooling',
    landingHomeschoolDesc: 'Tutto ciò di cui hai bisogno per un\'esperienza di homeschooling di successo.',
    landingAdaptiveLearning: 'Apprendimento Adattivo',
    landingAdaptiveLearningDesc: 'Percorsi di apprendimento che si adattano al ritmo di ogni bambino.',
    landingFullVisibility: 'Visibilità Totale',
    landingFullVisibilityDesc: 'Monitora i progressi in tempo reale con rapporti dettagliati.',
    landingFlexibleCurriculum: 'Curriculum Flessibile',
    landingFlexibleCurriculumDesc: 'Personalizza il curriculum in base alle esigenze della tua famiglia.',
    landing100Customizable: '100% Personalizzabile',
    landingDownloadLearn: 'Scarica e Impara',
    landingDownloadLearnDesc: 'Esporta materiali per l\'apprendimento offline.',
    landingPdfExportFeature: 'Esporta PDF',
    landingTextToSpeech: 'Testo in Voce',
    landingTextToSpeechDesc: 'Supporto audio per tutti i contenuti di lettura.',
    landingAudioLearning: 'Apprendimento Audio',
    landingSafeContent: 'Contenuto Sicuro',
    landingSafeContentDesc: 'Materiali appropriati all\'età e verificati.',
    landingParentalControl: 'Controllo Genitoriale',
    landingSubjectModules: 'Moduli per Materia',
    landingMathematics: 'Matematica',
    landingLanguageArts: 'Italiano',
    landingScience: 'Scienze',
    landingAstronomy: 'Astronomia',
    landingGeography: 'Geografia',
    landingHistory: 'Storia',
    landingArt: 'Arte',
    landingPhysicalEd: 'Educazione Fisica',
    landingStartHomeschooling: 'Inizia l\'Homeschooling',
    // CTA Section
    landing7DaysFree: '7 giorni gratis',
    landingGetStartedToday: 'Inizia oggi',
    landingStartYourJourney: 'Inizia il tuo percorso di classe digitale. Nessuna carta di credito richiesta.',
    landingNoCreditCard: 'Nessuna carta di credito richiesta',
    landingSetup2Min: 'Configurazione in 2 minuti',
    landingCancelAnytime: 'Annulla in qualsiasi momento',
    landingSupportBilingual: 'Supporto multilingue',
    landingActiveTeachers: 'insegnanti attivi',
    landingSignIn: 'Accedi',
    landingCreateAccountTab: 'Crea account',
    landingContinueGoogle: 'Continua con Google',
    landingOrWithEmail: 'o con email',
    landingEmail: 'Email',
    landingPassword: 'Password',
    landingFullNameLabel: 'Nome completo',
    landingCreateFreeAccount: 'Crea account gratuito',
    // Footer
    landingContact: 'Contatto',
    landingPrivacyPolicy: 'Informativa sulla Privacy',
    landingHelp: 'Aiuto',
    landingTermsOfUse: 'Termini di Utilizzo',
    landingCookiesPolicy: 'Informativa sui Cookie',
    landingAccessibility: 'Accessibilità',
    landingAllRightsReserved: 'Tutti i diritti riservati.'
  },
  zh: {
    // Navigation
    dashboard: '仪表板',
    planner: '课程计划',
    attendance: '考勤',
    gradebook: '成绩册',
    classes: '班级',
    settings: '设置',
    logout: '退出',
    
    // Auth
    login: '登录',
    register: '注册',
    email: '邮箱',
    password: '密码',
    name: '姓名',
    signInWithGoogle: '使用Google登录',
    orContinueWith: '或使用',
    dontHaveAccount: '没有账户？',
    alreadyHaveAccount: '已有账户？',
    
    // Dashboard
    welcome: '欢迎',
    todayOverview: '今日概览',
    quickActions: '快捷操作',
    attendancePending: '待处理考勤',
    upcomingAssignments: '即将到期作业',
    recentPlans: '最近计划',
    totalClasses: '班级总数',
    totalStudents: '学生总数',
    totalPlans: '计划总数',
    
    // Classes
    addClass: '添加班级',
    className: '班级名称',
    grade: '年级',
    section: '班组',
    subject: '科目',
    yearTerm: '学年/学期',
    students: '学生',
    addStudent: '添加学生',
    firstName: '名',
    lastName: '姓',
    studentNumber: '学号',
    parentEmail: '家长邮箱',
    notes: '备注',
    accommodations: '特殊安排',
    
    // Common
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    view: '查看',
    search: '搜索',
    filter: '筛选',
    loading: '加载中...',
    noData: '暂无数据',
    confirmDelete: '确定要删除吗？',
    success: '成功',
    error: '错误',
    from: '从',
    to: '到',
    date: '日期',
    teacher: '教师',
    selectLanguage: '选择语言',
    
    // Days
    monday: '星期一',
    tuesday: '星期二',
    wednesday: '星期三',
    thursday: '星期四',
    friday: '星期五',
    
    // Games
    educationalGames: '教育游戏',
    myGames: '我的游戏',
    createGame: '创建游戏',
    play: '开始',
    copyLink: '复制链接',
    shareToClassroom: '分享到Classroom',
    deleteGame: '删除游戏',
    questions: '问题',
    gameType: '游戏类型',
    gradeLevel: '年级水平',
    
    // Landing Page
    landingHeroTitle: '一个平台，完整的教室',
    landingHeroSubtitle: '课程计划、考勤、成绩和AI助手。教师所需的一切。',
    landingBuiltForTeachers: '专为教师打造',
    landingStartFree: '免费开始',
    landingViewPricing: '查看价格',
    landingUsedBySchools: '全球学校使用',
    landingEverythingYouNeed: '您需要的一切',
    landingEverythingDesc: '专为教师设计的完整平台。',
    landingFeatures: '功能',
    landingAiAssistant: 'AI助手',
    landingHomeschool: '家庭教育',
    landingIntegrations: '集成',
    landingCustomization: '定制',
    landingPricing: '价格',
    landingGetStarted: '开始 - 登录',
    landingStart: '开始',
    landingAiLessonPlan: 'AI计划',
    landingPresentations: '演示文稿',
    landingGrades: '成绩',
    landingPlanFaster: '更快地规划',
    landingPlanFasterDesc: '用我们直观的格式在几秒钟内创建每周课程计划。',
    landingWeek1: '第1周',
    landingYourBrand: '您的品牌，您的风格',
    landingYourBrandDesc: '使用您学校的标志和颜色进行个性化定制。',
    landingYourSchool: '您的学校',
    landingCustomBranding: '自定义品牌',
    landingExportPro: '专业导出',
    landingExportProDesc: '生成可打印的PDF：计划、成绩单、代课包。',
    landingDownloadPdf: '下载PDF',
    landingAiAssistantTitle: 'AI助手',
    landingAiAssistantDesc: '使用AI生成课程计划、活动和问题。',
    landingLessonPlans: '课程计划',
    landingQuizzesTests: '测验和考试',
    landingDigitalClassroom: '您的数字教室',
    landingTryFree: '免费试用30天',
    landingNoCard: '无需信用卡',
    landingFullName: '全名',
    landingCreateAccount: '创建免费账户',
    landingOrLoginWith: '或使用以下方式登录',
    landingHaveAccount: '已有账户？',
    landingLoginHere: '在此登录',
    landingNeedAccount: '需要账户？',
    landingRegisterHere: '在此注册'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('teacherhub_language') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('teacherhub_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const toggleLanguage = () => {
    // Cycle through languages
    const codes = availableLanguages.map(l => l.code);
    const currentIndex = codes.indexOf(language);
    const nextIndex = (currentIndex + 1) % codes.length;
    setLanguage(codes[nextIndex]);
  };

  const getCurrentLanguage = () => {
    return availableLanguages.find(l => l.code === language) || availableLanguages[0];
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      toggleLanguage, 
      getCurrentLanguage,
      availableLanguages 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
